/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    CronGen: typeof import('./../components/CronGen/index.vue')['default']
    Day: typeof import('./../components/CronGen/components/Day.vue')['default']
    Hour: typeof import('./../components/CronGen/components/Hour.vue')['default']
    Min: typeof import('./../components/CronGen/components/Min.vue')['default']
    Month: typeof import('./../components/CronGen/components/Month.vue')['default']
    NCard: typeof import('naive-ui')['NCard']
    NCheckbox: typeof import('naive-ui')['NCheckbox']
    NCheckboxGroup: typeof import('naive-ui')['NCheckboxGroup']
    NFlex: typeof import('naive-ui')['NFlex']
    NGi: typeof import('naive-ui')['NGi']
    NGrid: typeof import('naive-ui')['NGrid']
    NInputNumber: typeof import('naive-ui')['NInputNumber']
    NovaIcon: typeof import('./../components/NovaIcon/index.vue')['default']
    NRadio: typeof import('naive-ui')['NRadio']
    NRadioButton: typeof import('naive-ui')['NRadioButton']
    NRadioGroup: typeof import('naive-ui')['NRadioGroup']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    NTag: typeof import('naive-ui')['NTag']
    Result: typeof import('./../components/CronGen/components/Result.vue')['default']
    Second: typeof import('./../components/CronGen/components/Second.vue')['default']
    Week: typeof import('./../components/CronGen/components/Week.vue')['default']
    Year: typeof import('./../components/CronGen/components/Year.vue')['default']
  }
}
